var aa="function"==typeof Object.create?Object.create:function(e){function k(){}k.prototype=e;return new k},D;if("function"==typeof Object.setPrototypeOf)D=Object.setPrototypeOf;else{var J;a:{var ba={a:!0},K={};try{K.__proto__=ba;J=K.a;break a}catch(e){}J=!1}D=J?function(e,k){e.__proto__=k;if(e.__proto__!==k)throw new TypeError(e+" is not extensible");return e}:null}var M=D;
function N(e,k){e.prototype=aa(k.prototype);e.prototype.constructor=e;if(M)M(e,k);else for(var p in k)if("prototype"!=p)if(Object.defineProperties){var q=Object.getOwnPropertyDescriptor(k,p);q&&Object.defineProperty(e,p,q)}else e[p]=k[p];e.va=k.prototype}function O(){this.A=!1;this.m=null;this.G=void 0;this.o=1;this.P=this.ba=0;this.v=null}function P(e){if(e.A)throw new TypeError("Generator is already running");e.A=!0}O.prototype.B=function(e){this.G=e};
O.prototype.F=function(e){this.v={fa:e,ma:!0};this.o=this.ba||this.P};O.prototype["return"]=function(e){this.v={"return":e};this.o=this.P};function T(e){this.g=new O;this.qa=e}T.prototype.B=function(e){P(this.g);if(this.g.m)return U(this,this.g.m.next,e,this.g.B);this.g.B(e);return V(this)};function ca(e,k){P(e.g);var p=e.g.m;if(p)return U(e,"return"in p?p["return"]:function(q){return{value:q,done:!0}},k,e.g["return"]);e.g["return"](k);return V(e)}
T.prototype.F=function(e){P(this.g);if(this.g.m)return U(this,this.g.m["throw"],e,this.g.B);this.g.F(e);return V(this)};function U(e,k,p,q){try{var x=k.call(e.g.m,p);if(!(x instanceof Object))throw new TypeError("Iterator result "+x+" is not an object");if(!x.done)return e.g.A=!1,x;var v=x.value}catch(u){return e.g.m=null,e.g.F(u),V(e)}e.g.m=null;q.call(e.g,v);return V(e)}
function V(e){for(;e.g.o;)try{var k=e.qa(e.g);if(k)return e.g.A=!1,{value:k.value,done:!1}}catch(p){e.g.G=void 0,e.g.F(p)}e.g.A=!1;if(e.g.v){k=e.g.v;e.g.v=null;if(k.ma)throw k.fa;return{value:k["return"],done:!0}}return{value:void 0,done:!0}}function W(e){this.next=function(k){return e.B(k)};this["throw"]=function(k){return e.F(k)};this["return"]=function(k){return ca(e,k)};this[Symbol.iterator]=function(){return this}}
function X(e){function k(q){return e.next(q)}function p(q){return e["throw"](q)}return new Promise(function(q,x){function v(u){u.done?q(u.value):Promise.resolve(u.value).then(k,p).then(v,x)}v(e.next())})}
(function(){function e(b){this.current=0;this.N=b}function k(b){for(var a=b.length,c=1;a>1<<c;)++c;if(8<c||a!=1<<c)throw v.u();this.H=b;this.U=c}function p(){}function q(b){this.length=b.byteLength;this.b=new Uint8Array(b);this.b.aa=b;b.ja=this;b.ta=this.b}function x(b,a,c){a=v.call(this,String(b),a,c)||this;a.value=b;return a}function v(b){var a=Error.call(this,b);this.message=a.message;"stack"in a&&(this.stack=a.stack);this.message=b}function u(){}function r(){}function w(){this.elements=this.I=
this.C=null;null==w.da&&w.ka();var b=this;window.fetch("elements.txt").then(function(a){return a.text()}).then(function(a){return w.S(a)}).then(function(a){a=JSON.parse(a);b.elements=a;return window.fetch("recipes.txt").then(function(c){return c.text()}).then(function(c){return w.S(c)}).then(function(c){c=JSON.parse(c);b.I=c;var d=b.elements;c=Array(d.length);var h=0;for(d=d.length;h<d;)c[h++]=[];b.C=c;c=0;for(h=b.I;c<h.length;)d=h[c],++c,-1!=d[2]&&b.C[d[2]].push([d[0],d[1]]);c=0;for(h=b.C;c<h.length;)h[c++].sort(function(m,
n){var y=b.elements[m[0]].dist,A=b.elements[m[1]].dist,g=b.elements[n[0]].dist,f=b.elements[n[1]].dist;return 1E4*(y>A?y:A)+b.elements[m[0]].dist+b.elements[m[1]].dist-(1E4*(g>f?g:f)+b.elements[n[0]].dist+b.elements[n[1]].dist)});b.start()})})}function Q(){}function L(){}function z(){}z.O=function(b,a){var c=b.charCodeAt(a);if(c==c)return c};z.substr=function(b,a,c){if(null==c)c=b.length;else if(0>c)if(0==a)c=b.length+c;else return"";return b.substr(a,c)};z.now=function(){return Date.now()};z.h=!0;L.empty=function(b){return!(b instanceof
Array?new e(b):b.iterator()).ia()};L.h=!0;Q.oa=function(){new w};Q.h=!0;Math.h=!0;w.prototype.start=function(){function b(g){var f=d.elements.indexOf(g);if(-1==f)throw v.u();c.innerHTML="";g=[];for(var t=0,l={};200>t;){l={l:l.l,s:l.s,D:l.D};++t;var C=d.elements,Y=Array(C.length),Z=0;for(C=C.length;Z<C;)Y[Z++]=!1;l.l=Y;l.D=[];l.s=null;l.s=function(E){return function(F){if(!E.l[F]){for(var G=d.elements[F].dist,H=d.C[F],B=[],R=0;R<H.length;){var S=H[R];++R;d.elements[S[0]].dist<G&&d.elements[S[1]].dist<G&&B.push(S)}G=
B.length-1;H=-Math.log(Math.random())/.6931471805599453|0;B=B[G<H?G:H];(0,E.s)(B[0]);(0,E.s)(B[1]);E.D.push([B[0],B[1],F]);E.l[F]=!0}}}(l);l.l[0]=!0;l.l[1]=!0;l.l[2]=!0;l.l[3]=!0;l.l[4]=!0;(0,l.s)(f);if(L.empty(g)||l.D.length<g.length)g=l.D}for(f=0;f<g.length;)t=g[f],++f,l=a.createElement("div"),l.textContent=d.j(d.elements[t[0]])+" + "+d.j(d.elements[t[1]])+" = "+d.j(d.elements[t[2]]),c.append(l)}var a=window.document,c=a.getElementById("main"),d=this,h=a.getElementById("name"),m=a.getElementById("go"),
n=a.getElementById("path"),y=a.getElementById("random"),A=a.getElementById("search");a.addEventListener("keydown",function(g){"Enter"==g.code&&m.click()});m.addEventListener("click",function(){var g=d.R(u.trim(h.value));if(null!=g){var f=d.elements.indexOf(g);if(-1==f)throw v.u();c.innerHTML="";var t=0;for(f=d.C[f];t<f.length;){var l=f[t];++t;var C=a.createElement("div");C.textContent=d.j(d.elements[l[0]])+" + "+d.j(d.elements[l[1]])+" = "+d.j(g);c.append(C)}}});n.addEventListener("click",function(){var g=
d.R(u.trim(h.value));null!=g&&b(g)});y.addEventListener("click",function(){for(var g=d.I,f=[],t=0;t<g.length;){var l=g[t];++t;-1!=l[2]&&f.push(l)}g=[];g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);
g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);g.push(f[r.random(f.length)]);c.innerHTML="";for(f=0;f<g.length;)t=g[f],++f,l=a.createElement("div"),l.textContent=d.j(d.elements[t[0]])+" + "+d.j(d.elements[t[1]])+" = "+d.j(d.elements[t[2]]),c.append(l)});A.addEventListener("click",function(){var g=d.ga(u.trim(h.value));c.innerHTML="";for(var f=
0;f<g.length;){var t=g[f++],l=a.createElement("div");l.textContent=d.j(t);c.append(l)}})};w.prototype.j=function(b){return b.emoji+" "+b.text};w.prototype.ga=function(b){if(""==b)return[];for(var a=[],c=0,d=this.elements;c<d.length;){var h=d[c];++c;-1!=h.text.toLowerCase().indexOf(b.toLowerCase())&&a.push(h)}a.sort(function(m,n){return m.dist-n.dist});return a};w.prototype.R=function(b){for(var a=[],c=0,d=this.elements;c<d.length;){var h=d[c];++c;h.text.toLowerCase()==b.toLowerCase()&&a.push(h)}a.sort(function(m,
n){return m.dist-n.dist});if(L.empty(a))return null;if(0>=a.length)throw v.u();return a[0]};w.ka=function(){function b(c){var d,h,m;return X(new W(new T(function(n){if(1==n.o){d=(new Blob([c])).stream();h=d.pipeThrough(new DecompressionStream("gzip"));var y=(new Response(h)).arrayBuffer();n.o=2;return{value:y}}m=n.G;return n["return"]((new TextDecoder).decode(m))})))}function a(c){var d,h;return X(new W(new T(function(m){if(1==m.o){d=(new Blob([c])).stream();h=d.pipeThrough(new CompressionStream("gzip"));
var n=(new Response(h)).arrayBuffer();m.o=2;return{value:n}}return m["return"](m.G)})))}w.da=function(c){return a(c).then(function(d){return p.encode(q.pa(d))})};w.S=function(c){return b(p.decode(c).b.aa)}};w.h=!0;r.random=function(b){return 0>=b?0:Math.floor(Math.random()*b)};r.h=!0;u.T=function(b,a){var c=z.O(b,a);return 8<c&&14>c?!0:32==c};u.na=function(b){for(var a=b.length,c=0;c<a&&u.T(b,c);)++c;return 0<c?z.substr(b,c,a-c):b};u.ra=function(b){for(var a=b.length,c=0;c<a&&u.T(b,a-c-1);)++c;return 0<
c?z.substr(b,0,a-c):b};u.trim=function(b){return u.na(u.ra(b))};u.h=!0;N(v,Error);v.u=function(){return new x("")};v.h=!0;N(x,v);x.h=!0;q.prototype.ha=function(b){if(0>b||0+b>this.length)throw v.u();if(null==a)var a=I.L;var c="",d=this.b,h=0;b=0+b;switch(a.M){case 0:for(;h<b;)if(a=d[h++],128>a){if(0==a)break;c+=String.fromCodePoint(a)}else 224>a?(a=(a&63)<<6|d[h++]&127,c+=String.fromCodePoint(a)):240>a?(a=(a&31)<<12|(d[h++]&127)<<6|d[h++]&127,c+=String.fromCodePoint(a)):(a=(a&15)<<18|(d[h++]&127)<<
12|(d[h++]&127)<<6|d[h++]&127,c+=String.fromCodePoint(a));break;case 1:for(;h<b;)a=d[h++]|d[h++]<<8,c+=String.fromCodePoint(a)}return c};q.prototype.toString=function(){return this.ha(this.length)};q.V=function(b){if(void 0==I.K){for(var a=new Uint8Array(b.length<<1),c=0,d=b.length;c<d;){var h=c++,m=b.charCodeAt(h);a[h<<1]=m&255;a[h<<1|1]=m>>8}return new q(a.buffer)}a=[];for(c=0;c<b.length;)d=b.charCodeAt(c++),55296<=d&&56319>=d&&(d=d-55232<<10|b.charCodeAt(c++)&1023),127>=d?a.push(d):(2047>=d?a.push(192|
d>>6):(65535>=d?a.push(224|d>>12):(a.push(240|d>>18),a.push(128|d>>12&63)),a.push(128|d>>6&63)),a.push(128|d&63));return new q((new Uint8Array(a)).buffer)};q.pa=function(b){var a=b.ja;return null!=a?a:new q(b)};q.h=!0;var I={sa:!0,Y:null,L:{$:"UTF8",M:0,Z:"E"},K:{$:"RawNative",M:1,Z:"E"}};I.Y=[I.L,I.K];p.encode=function(b,a){null==a&&(a=!0);var c=(new k(p.J)).ea(b).toString();if(a)switch(b.length%3){case 1:c+="==";break;case 2:c+="="}return c};p.decode=function(b,a){null==a&&(a=!0);if(a)for(;61==
z.O(b,b.length-1);)b=z.substr(b,0,-1);return(new k(p.J)).ca(q.V(b))};p.h=!0;k.prototype.ea=function(b){for(var a=this.U,c=this.H,d=8*b.length/a|0,h=new q(new ArrayBuffer(d+(0==8*b.length%a?0:1))),m=0,n=0,y=(1<<a)-1,A=0,g=0;g<d;){for(;n<a;)n+=8,m<<=8,m|=b.b[A++];n-=a;h.b[g++]=c.b[m>>n&y]}0<n&&(h.b[g++]=c.b[m<<a-n&y]);return h};k.prototype.la=function(){for(var b=[],a=0;256>a;)b[a++]=-1;a=0;for(var c=this.H.length;a<c;){var d=a++;b[this.H.b[d]]=d}this.W=b};k.prototype.ca=function(b){var a=this.U;null==
this.W&&this.la();for(var c=this.W,d=b.length*a>>3,h=new q(new ArrayBuffer(d)),m=0,n=0,y=0,A=0;A<d;){for(;8>n;){n+=a;m<<=a;var g=c[b.b[y++]];if(-1==g)throw v.u();m|=g}n-=8;h.b[A++]=m>>n&255}return h};k.h=!0;e.prototype.ia=function(){return this.current<this.N.length};e.prototype.next=function(){return this.N[this.current++]};e.h=!0;"undefined"!=typeof performance&&"function"==typeof performance.now&&(z.now=performance.now.bind(performance));null==String.fromCodePoint&&(String.fromCodePoint=function(b){return 65536>
b?String.fromCharCode(b):String.fromCharCode((b>>10)+55232)+String.fromCharCode((b&1023)+56320)});String.h=!0;Array.h=!0;p.X="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";p.J=q.V(p.X);Q.oa()})({});